version: '3'

services:

    ez:
        image: ${COMPOSE_PROJECT_NAME:-euts}_ez
        build:
            context: images/ez
            args:
                os_vendor: ${TESTSTACK_OS_VENDOR:-debian}
                debian_version: ${TESTSTACK_DEBIAN_VERSION:-buster}
                debian_mirror: ${TESTSTACK_DEBIAN_MIRROR:-none}
                do_update_os: ${TESTSTACK_UPDATE_OS_ON_BUILD:-true}
                php_version: ${TESTSTACK_PHP_VERSION:-default}
                node_version: ${TESTSTACK_NODE_VERSION:-default}
                project_name: ${COMPOSE_PROJECT_NAME:-euts}
                timezone: ${TESTSTACK_TZ:-none}
        hostname: ez
        container_name: ${COMPOSE_PROJECT_NAME:-euts}_ez
        environment:
            ## Configuration used by the boot/setup scripts
            - CONTAINER_USER_UID=${CONTAINER_USER_UID:-1000}
            - CONTAINER_USER_GID=${CONTAINER_USER_GID:-1000}
            - http_proxy
            - https_proxy
            # Composer configuration
            - COMPOSER_AUTH
            - COMPOSER_IGNORE_PLATFORM_REQS
            - COMPOSER_MAX_PARALLEL_HTTP
            - COMPOSER_PREFER_LOWEST
            - COMPOSER_PROCESS_TIMEOUT
            # Note that leaving this an empty default ha an effect on the name of the vendor folder and composer files which get set up
            - COMPOSE_PROJECT_NAME
            - TESTSTACK_SETUP_APP_ON_BOOT
            # unluckily using PHP_VERSION=${TESTSTACK_PHP_VERSION:-${PHP_VERSION}} does not work
            - TESTSTACK_PHP_VERSION
            - TESTSTACK_NODE_VERSION
            ## Database configuration
            - DB_TYPE=${DB_TYPE:-mysql}
            - DB_HOST
            - MYSQL_VERSION=${MYSQL_VERSION:-5.6}
            - POSTGRESQL_VERSION=${POSTGRESQL_VERSION:-9.5}
            - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_test}
            - DB_CHARSET
            - DB_EZ_USER=${DB_EZ_USER:-ezp}
            - DB_EZ_PASSWORD=${DB_EZ_PASSWORD:-ezp}
            - DB_EZ_DATABASE=${DB_EZ_DATABASE:-behattestdb}
            ## Configuration for the eZ test env to set up
            - EZ_PACKAGES
            - EZ_COMPOSER_LOCK
            - EZ_BUNDLES
            - EZ_LEGACY_EXTENSIONS
            # Name of a symfony config file containing parameters and services used by the tests
            - EZ_TEST_CONFIG_SYMFONY
            # Configuration used by Symfony when running via phpunit (SYMFONY_ENV up to eZPlatform 2, APP_ENV for eZPlatform3)
            - APP_ENV=${APP_ENV:-behat}
            - SYMFONY_ENV=${SYMFONY_ENV:-behat}
            # As opposed to TRAVIS=true ;-)
            - DOCKER=true
        volumes:
            - ../:/home/test/teststack
            - ${TESTSTACK_APP_DIR:-../../}:/home/test/workspace
            - ${TESTSTACK_DATA_DIR:-./data}/.composer/:/home/test/.composer

#networks:
#    default:
#        ipam:
#            config:
#                - subnet: "${TESTSTACK_SUBNET:-172.19.30}.0/24"
