version: '3'

services:

    postgresql:
        image: ${COMPOSE_PROJECT_NAME:-euts}_postgresql
        build:
            context: images/postgresql
            args:
                do_update_os: ${TESTSTACK_UPDATE_OS_ON_BUILD:-true}
                # note: Travis Xenial images come with PG 9.4-9.6,10; Bionic with 9.3-9.6,10,11 and Focal with 12
                #       We go with 11 as default because it is the lowest upstream supported version as of 4/2023...
                postgresql_version: ${POSTGRESQL_VERSION:-11}
                project_name: ${COMPOSE_PROJECT_NAME:-euts}
                timezone: ${TESTSTACK_TZ:-none}
        hostname: postgresql
        container_name: ${COMPOSE_PROJECT_NAME:-euts}_postgresql
        environment:
            - CONTAINER_USER_UID=${CONTAINER_USER_UID:-1000}
            - CONTAINER_USER_GID=${CONTAINER_USER_GID:-1000}
            - DB_TYPE=postgresql
            # This is a courtesy - inside the container we should be able to retrieve the installed db version easily...
            - POSTGRESQL_VERSION
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root_test}
            - EZ_PACKAGES
            # As opposed to TRAVIS=true ;-)
            - DOCKER=true
        volumes:
            - ${TESTSTACK_DATA_DIR:-./data}/postgresql/${COMPOSE_PROJECT_NAME:-euts}/:/var/lib/postgresql
            - ${TESTSTACK_LOGS_DIR:-./logs}/postgresql/${COMPOSE_PROJECT_NAME:-euts}/:/var/log/postgresql
            # @todo in case we have to run some db configuration based on eZ version, we should mount db-config.sh
            #- ../:/home/test/teststack
        # uncomment this to be able to access the db from the host
        #ports:
        #    - "5433:5432"
