# This file will replace (and then include) the equivalent one from Ibexa distribution
# Used to set up an Ibexa env from scratch for testing purposes (eg. on GHA)

imports:
    - { resource: ibexa_orig.yaml }
    - { resource: ../config_behat.php }

parameters:
    ibexa.kernel.root_dir: "%kernel.project_dir%/../../../vendor/ibexa/core"
    ibexa.field_type.richtext.resources: '%kernel.project_dir%/../../../vendor/ibexa/fieldtype-richtext/src/bundle/Resources/richtext'
    ibexa.site_access.config.default.fieldtypes.ezrichtext.output_custom_xsl:
        -
            path: '%kernel.project_dir%/../../../vendor/ibexa/fieldtype-richtext/src/bundle/Resources/richtext/stylesheets/docbook/xhtml5/output/core.xsl'
            priority: 0

    ibexa.site_access.config.default.fieldtypes.ezrichtext.edit_custom_xsl:
        -
            path: '%kernel.project_dir%/vendor/../../../ibexa/fieldtype-richtext/src/bundle/Resources/richtext/stylesheets/docbook/xhtml5/edit/core.xsl'
            priority: 0

    # @todo see https://github.com/tanoconsulting/ibexa-migration-bundle/commit/5a213d8ee45f5b0cf0235c4bc4c852b0fc1f17ca
    #       for something we could have to add here for all projects using this stack
doctrine:
    dbal:
        server_version: '%database_version%'
        url: 'mysql://%database_user%:%database_password%@%database_host%:3306/%database_name%'
